# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vector_query.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'vector_query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12vector_query.proto\x12\x0bvectorquery\"\x1d\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x1f\n\rQueryResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2\\\n\x12VectorQueryService\x12\x46\n\rFetchAndQuery\x12\x19.vectorquery.QueryRequest\x1a\x1a.vectorquery.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=35
  _globals['_QUERYREQUEST']._serialized_end=64
  _globals['_QUERYRESPONSE']._serialized_start=66
  _globals['_QUERYRESPONSE']._serialized_end=97
  _globals['_VECTORQUERYSERVICE']._serialized_start=99
  _globals['_VECTORQUERYSERVICE']._serialized_end=191
# @@protoc_insertion_point(module_scope)
