# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: personalization.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'personalization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15personalization.proto\x12\x0fpersonalization\"*\n\x16PersonalizationRequest\x12\x10\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x01 \x01(\t\"I\n\x0e\x43\x61tegoryResult\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x17\n\x0fsentiment_score\x18\x03 \x01(\x02\"\xee\x01\n\x17PersonalizationResponse\x12\x33\n\ncategories\x18\x01 \x03(\x0b\x32\x1f.personalization.CategoryResult\x12\x10\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x02 \x01(\t\x12U\n\x0f\x63\x61tegory_counts\x18\x03 \x03(\x0b\x32<.personalization.PersonalizationResponse.CategoryCountsEntry\x1a\x35\n\x13\x43\x61tegoryCountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32\x86\x01\n\x16PersonalizationService\x12l\n\x17GeneratePersonalization\x12\'.personalization.PersonalizationRequest\x1a(.personalization.PersonalizationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'personalization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSONALIZATIONRESPONSE_CATEGORYCOUNTSENTRY']._loaded_options = None
  _globals['_PERSONALIZATIONRESPONSE_CATEGORYCOUNTSENTRY']._serialized_options = b'8\001'
  _globals['_PERSONALIZATIONREQUEST']._serialized_start=42
  _globals['_PERSONALIZATIONREQUEST']._serialized_end=84
  _globals['_CATEGORYRESULT']._serialized_start=86
  _globals['_CATEGORYRESULT']._serialized_end=159
  _globals['_PERSONALIZATIONRESPONSE']._serialized_start=162
  _globals['_PERSONALIZATIONRESPONSE']._serialized_end=400
  _globals['_PERSONALIZATIONRESPONSE_CATEGORYCOUNTSENTRY']._serialized_start=347
  _globals['_PERSONALIZATIONRESPONSE_CATEGORYCOUNTSENTRY']._serialized_end=400
  _globals['_PERSONALIZATIONSERVICE']._serialized_start=403
  _globals['_PERSONALIZATIONSERVICE']._serialized_end=537
# @@protoc_insertion_point(module_scope)
