# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import personalization_pb2 as personalization__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in personalization_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PersonalizationServiceStub(object):
    """Service definition for generating personalization data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GeneratePersonalization = channel.unary_unary(
                '/personalization.PersonalizationService/GeneratePersonalization',
                request_serializer=personalization__pb2.PersonalizationRequest.SerializeToString,
                response_deserializer=personalization__pb2.PersonalizationResponse.FromString,
                _registered_method=True)


class PersonalizationServiceServicer(object):
    """Service definition for generating personalization data
    """

    def GeneratePersonalization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PersonalizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GeneratePersonalization': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePersonalization,
                    request_deserializer=personalization__pb2.PersonalizationRequest.FromString,
                    response_serializer=personalization__pb2.PersonalizationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'personalization.PersonalizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('personalization.PersonalizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PersonalizationService(object):
    """Service definition for generating personalization data
    """

    @staticmethod
    def GeneratePersonalization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/personalization.PersonalizationService/GeneratePersonalization',
            personalization__pb2.PersonalizationRequest.SerializeToString,
            personalization__pb2.PersonalizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
